apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  application.yml: |-
    server:
      port: 4004
    spring:
      application:
        name: gateway-service
      cloud:
        gateway:
          routes:
            - id: product-service-route
              uri: http://product-service:8080
              predicates:
                - Path=/api/products/**
              filters:
                - StripPrefix=2
    # Disable Eureka client since we are using Kubernetes service discovery
    eureka:
      client:
        enabled: false